use march;
INSERT INTO product ( brand , product ) VALUES
('JOYSOUND' , 'WAVE') ,
('JOYSOUND' , 'CROSSO') ,
('JOYSOUND' , 'f1') ,
('JOYSOUND' , 'MAX') ,
('DAM' , 'Premier DAM') ,
('DAM' , 'LIVE DAM');

INSERT INTO score_type ( brand , name ) VALUES
('JOYSOUND' , '全国採点オンライン２') ,
('JOYSOUND' , '全国採点オンライン３') ,
('JOYSOUND' , '分析採点１') ,
('JOYSOUND' , '分析採点２') ,
('JOYSOUND' , '分析採点３') ,
('DAM' , 'ランキングバトル') ,
('DAM' , '精密採点２') ,
('DAM' , '精密採点DX');

insert into store ( name , branch , url , memo ) VALUES
('歌広場' , '亀戸店' , 'http://www.utahiro.com/store/storelist/storeinfo/tabid/64/pdid/0105/Default.aspx' , '壁がめっちゃうすい') ,
('JOYJOY' , '甚目寺店' , 'http://www.joyjoy.co.jp/shop_detail.html?id=12' , 'プロジェクタ壁に映してる');

insert into artist ( name ) VALUES
('BUMP OF CHICKEN') ,
('野川 さくら') ,
('サザンオールスターズ') ,
('きゃりーぱみゅぱみゅ') ,
('Superfly') ,
('A応P') ,
('イヤミ(鈴村健一) feat.おそ松(櫻井孝宏)×カラ松(中村悠一)×チョロ松(神谷浩史)×一松(福山潤)×十四松(小野大輔)×トド松(入野自由)') ,
('UNISON SQUARE GARDEN') ,
('りぶ') ,
('島谷ひとみ') ,
('Last Note') ,
('SEKAI NO OWARI') ,
('トーマ') ,
('コブクロ') ,
('一ノ瀬トキヤ(宮野真守)') ,
('Supercell') ,
('シド') ,
('TOKIO'),
('宮野真守'),
('MYTH & ROID') ,
('聖川真斗(鈴村健一)、一ノ瀬トキヤ(宮野真守)') ,
('ST☆RISH') ,
('ゴールデンボンバー') ,
('きただにひろし') ,
('木山裕策') ,
('アン・ルイス') ,
('松任谷由実') ,
('今井美樹') ,
('Every Little Thing') ,
('のぼる↑') ,
('Neru') ,
('kemu') ,
('UVERworld') ,
('164') ,
('遠藤正明') ,
('TRUE') ,
('高坂麗奈（CV.安済知佳）') ,
('ALL OFF') ,
('SPYAIR') ,
('水樹奈々') ,
('槇原敬之') ,
('Fire Bomber') ,
('Deen') ,
('the brilliant green') ,
('福山雅治') ,
('coba＆宮沢和史') ,
('JAM Project') ,
('Hilcrhyme') ,
('上木彩矢') ,
('FENCE OF DEFENSE') ,
('FLOW') ,
('ポルノグラフィティ') ,
('WANDS');

INSERT INTO user ( username , password , screenname ) VALUES
('sa2knight' , 'zenra' , 'ないと') ,
('unagipai' , 'zenra' , 'ちゃらさん') ,
('hetare' , 'zenra' , 'へたれ') ,
('worry' , 'zenra' , 'ウォーリー');

INSERT INTO song ( artist , name , url ) VALUES
(1 , 'オンリーロンリーグローリー' , 'https://www.youtube.com/watch?v=ZpAn8moiAOM') ,
(1 , '天体観測' , 'https://www.youtube.com/watch?v=j7CDb610Bg0') ,
(2 , 'HAPPY HARMONICS' , 'https://www.youtube.com/watch?v=iPVL2eYEDDQ') ,
(3 , 'TSUNAMI' , 'https://www.youtube.com/watch?v=HgDGFrMITOo') ,
(4 , 'PONPONPON' , 'https://www.youtube.com/watch?v=yzC4hFK5P3g') ,
(5 , '輝く月のように' , 'https://www.youtube.com/watch?v=gG7evVU0OdA') ,
(6 , 'はなまるぴっぴはよいこだけ' , 'https://www.youtube.com/watch?v=-AawjV4eJPA') ,
(7 , 'SIX SAME FACES' , 'https://www.youtube.com/watch?v=RVB6E03-9m8') ,
(8 , 'シュガーソングとビターステップ' , 'https://www.youtube.com/watch?v=3exsRhw3xt8') ,
(9 , 'ヨンジュウナナ' , 'https://www.youtube.com/watch?v=YICM_U1EwLM') ,
(10 , 'YUME日和' , 'https://www.youtube.com/watch?v=LuNmfDmeCTc') ,
(11 , 'セツナトリップ' , 'https://www.youtube.com/watch?v=EXxW1GWSdps') ,
(12 , 'RPG' , 'https://www.youtube.com/watch?v=Mi9uNu35Gmk') ,
(13 , 'ヤンキーボーイ・ヤンキーガール' , 'https://www.youtube.com/watch?v=v5S1kdPc8LA') ,
(14 , 'ここにしか咲かない花' , 'https://www.youtube.com/watch?v=aa8iVP-9M5w') ,
(15 , 'Independence' , 'https://www.youtube.com/watch?v=QPmoTAmcVGk') ,
(16 , 'ワールドイズマイン' , 'https://www.youtube.com/watch?v=YGYaOLTVDR8') ,
(1 , 'ダイヤモンド' , 'https://www.youtube.com/watch?v=zATrOuOUu3E') ,
(17 , '嘘' , 'https://www.youtube.com/watch?v=LbZXvmXvNQQ') ,
(18 , '宙船(そらふね)' , 'https://www.youtube.com/watch?v=UpcDdLQgVVE') ,
(19 , 'オルフェ' , '') ,
(20 , 'LLL' , '') ,
(21 , 'ORIGINAL RESONANCE' , '') ,
(22 , 'マジLOVEレボリューションズ' , '') ,
(8 , 'オリオンをなぞる' , '') ,
(23 , '女々しくて' , '') ,
(24 , 'ウィーアー!' , '') ,
(25 , 'home' , '') ,
(26 , 'WOMAN' , '') ,
(27 , 'やさしさに包まれたなら' , '') ,
(28 , 'PIECE OF MY WISH' , '') ,
(29 , 'モノクローム' , '') ,
(30 , 'ショットガン・ラヴァーズ' , '') ,
(31 , 'ロストワンの号哭' , '') ,
(32 , '地球最後の告白を' , '') ,
(33 , 'REVERSI' , '') ,
(12 , 'Dragon Night' , '') ,
(34 , '天ノ弱' , '') ,
(35 , '勇者王誕生！' , '') ,
(36 , 'DREAM SOLISTER' , '') ,
(37 , '心響プロジェクター' , ''),
(38 , 'One More Chance!!' , '') ,
(15 , 'SECRET LOVER' , '') ,
(33 , 'クオリア' , '') ,
(39 , 'サムライハート(Some Like It Hot!!)' , '') ,
(40 , 'You have a dream' , '') ,
(41 , 'Hungry Spider' , '') ,
(42 , 'HOLLY LONELY LIGHT' , '') ,
(42 , 'Remember 16' , '') ,
(43 , '夢であるように' , '') ,
(44 , 'Ash Like Snow' , '') ,
(40 , 'Orchestral Fantasia' , '') ,
(33 , 'マダラ蝶' , '') ,
(33 , '儚くも永久のカナシ' , '') ,
(45 , '心color～a song for the wonderful year～' , '') ,
(46 , 'ひとりぼっちじゃない' , '') ,
(47 , 'THE HERO!!～怒れる拳に火をつけろ～' , '') ,
(48 , '春夏秋冬' , '') ,
(49 , 'ピエロ' , '') ,
(50 , 'セイラ～SARA～' , '') ,
(51 , 'COLORS' , '') ,
(52 , 'メリッサ' , '') ,
(53 , '世界が終わるまでは・・・' , '');

INSERT INTO karaoke ( datetime , name , plan , store , product) VALUES
('2016-01-03 15:30:00' , 'ともちんとないとのフタカラ' ,  3.5 , 1 , 5) ,
('2016-01-08 00:28:00' , '新年初カラオケ' , 5 , 2 , 4);

INSERT INTO attendance ( user , karaoke , price , memo ) VALUES
(1 , 1 , 1300 , 'なんか全体的に下手だった') ,
(3 , 2 , 1050 , '提供へたれ') ,
(4 , 2 , 1350 , '提供へたれ');

INSERT INTO history ( attendance , song , songkey , score_type , score) VALUES
(1 ,1 , 0 , 7 , 84 ) ,
(1 ,2 , 0 , 7 , 83 ) ,
(1 ,3 , 5 , 7 , 79 ) ,
(1 ,4 , 0 , 7 , 79 ) ,
(1 ,5 , -3 , 7 , 67 ) ,
(1 ,6 , 5 , 7 , 80 ) ,
(1 ,7 , 0 , 7 , 77 ) ,
(1 ,8 , 0 , 7 , 65 ) ,
(1 ,9 , -2 , 7 , 83 ) ,
(1 ,10 , 0 , 7 , 83 ) ,
(1 ,11 , -4 , 6 , 81.416) ,
(1 ,12 , 5 , 7 , 77 ) ,
(1 ,13 , 0 , 7 , 82 ) ,
(1 ,14 , 0 , 7 , 75 ) ,
(1 ,15 , 0 , 7 , 78 ) ,
(1 ,16 , 0 , 7 , 79 ) ,
(1 ,17 , 5 , 7 , 79 ) ,
(1 ,18 , 0 , 7 , 80 ) ,
(1 ,19 , 0 , 7 , 76 ) ,
(1 ,20 , 0 , 7 , 81 ) ,
(1 ,7 , 0 , 7 , 74 ) ,
(2 ,21 , 0 , null , null) ,
(2 ,22 , 0 , null , null) ,
(2 ,23 , 0 , null , null) ,
(2 ,24 , 0 , null , null) ,
(2 ,25 , 0 , null , null) ,
(2 ,26 , 0 , null , null) ,
(2 ,27 , 0 , null , null) ,
(2 ,28 , 0 , null , null) ,
(2 ,29 , 0 , null , null) ,
(2 ,30 , 0 , null , null) ,
(2 ,31 , 0 , null , null) ,
(2 ,32 , 0 , null , null) ,
(2 ,33 , 0 , null , null) ,
(2 ,34 , 0 , null , null) ,
(2 ,35 , 0 , null , null) ,
(2 ,36 , 0 , null , null) ,
(2 ,37 , 0 , null , null) ,
(2 ,38 , 0 , null , null) ,
(2 ,39 , 0 , null , null) ,
(2 ,40 , 0 , null , null) ,
(2 ,41 , 0 , null , null) ,
(2 ,42 , 0 , null , null) ,
(2 ,43 , 0 , null , null) ,
(2 ,44 , 0 , null , null) ,
(3 ,39 , 0 , null , null) ,
(3 ,45 , 0 , null , null) ,
(3 ,46 , 0 , null , null) ,
(3 ,47 , 0 , null , null) ,
(3 ,48 , 0 , null , null) ,
(3 ,49 , 0 , null , null) ,
(3 ,50 , 0 , null , null) ,
(3 ,51 , 0 , null , null) ,
(3 ,52 , 0 , null , null) ,
(3 ,53 , 0 , null , null) ,
(3 ,54 , 0 , null , null) ,
(3 ,55 , 0 , null , null) ,
(3 ,56 , 0 , null , null) ,
(3 ,57 , 0 , null , null) ,
(3 ,58 , 0 , null , null) ,
(3 ,59 , 0 , null , null) ,
(3 ,60 , 0 , null , null) ,
(3 ,61 , 0 , null , null) ,
(3 ,62 , 0 , null , null) ,
(3 ,63 , 0 , null , null);
